version: '3'

services:
  roundcubemail:
    build: .
    env_file:
      - .env
    environment:
      ROUNDCUBEMAIL_DB_TYPE: mysql
      ROUNDCUBEMAIL_SKIN: elastic
      ROUNDCUBEMAIL_DEFAULT_HOST: tls://mail.proyeccionlaboral.com
      ROUNDCUBEMAIL_SMTP_SERVER: tls://mail.proyeccionlaboral.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcube.rule=Host(`webmail.proyeccionlaboral.com`)"
      - "traefik.http.routers.roundcube.entrypoints=websecure"
      - "traefik.http.routers.roundcube.tls.certresolver=myresolver"
      - "traefik.http.services.roundcube.loadbalancer.server.port=80"
    depends_on:
      - db
    networks:
      - dokploy-network

  db:
    image: mariadb:10.5
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./var/roundcube/db/mysql:/var/lib/mysql
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
