services:
  roundcubemail:
    build: .
    volumes:
      - ./var/roundcube/db/sqlite:/var/roundcube/db
      - ./var/roundcube/config:/config
    environment:
      ROUNDCUBEMAIL_DB_TYPE: sqlite
      ROUNDCUBEMAIL_SKIN: elastic
      ROUNDCUBEMAIL_DEFAULT_HOST: tls://mail.proyeccionlaboral.com
      ROUNDCUBEMAIL_SMTP_SERVER: tls://mail.proyeccionlaboral.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcube.rule=Host(`webmail.proyeccionlaboral.com`)"
      - "traefik.http.routers.roundcube.entrypoints=websecure"
      - "traefik.http.routers.roundcube.tls.certresolver=myresolver"
      - "traefik.http.services.roundcube.loadbalancer.server.port=80"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true